import type { Metadata } from "next";
import { Geist, Geist_Mono, IBM_Plex_Sans, Rajdhani,Orbitron, Exo_2 } from "next/font/google";
import "./globals.css";
import SideBar from '@/components/AnimatedSidebar';
import { ReactNode } from 'react';

// Fonts
const rajdhani = Rajdhani({
  weight: ['300', '400'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-rajdhani',
});
const orbitron = Orbitron({ variable:'--font-orbitron', weight: ['400', '500'], subsets: ['latin'] });
const exo2 = Exo_2({ variable:'--font-exo2', weight: ['300', '400'], subsets: ['latin'] });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const ibmPlex = IBM_Plex_Sans({
  weight: ['100', '200', '300', '400'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-ibm-plex',
});

// Metadata
export const metadata: Metadata = {
  title: "Snitch",
  description: "Generated by create next app",
  icons: {
    icon: '/project/spying.png', // or '/favicon.ico' if you prefer
  },
};

// Layout
export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en" className={`${orbitron.variable} ${exo2.variable} ${rajdhani.variable} ${geistSans.variable} ${geistMono.variable} ${ibmPlex.variable}`}>
      <body className="flex">
        <SideBar />
        {children}
      </body>
    </html>
  );
}
